const DATABASE_NAME = '@worldacai'

const COLLECTION_USERS = `${DATABASE_NAME}:user`
const COLLECTION_ORDERS = `${DATABASE_NAME}:orders`
const COLLECTION_ADDRESS = `${COLLECTION_USERS}:address`

export {
    COLLECTION_USERS,
    COLLECTION_ORDERS,
    COLLECTION_ADDRESS
}